### PR TITLE
Task/zen 2471b

### PR DESCRIPTION
**Pull request by andylowry**
@tedepstein I think this is ready for an initial push. Please check things out, and merge if you agree. If you want anyone to review the overall site design - including some custom css and use of liquid templates, overall jekyll structure, and some shell scripts for publishing and installing jekyll locally, please assign that task.

I've been publishing with the "-f" (force) option on my publish script, which skips normal policy checks. Once this PR is merged, then going forward the process will be to omit "-f", which will refuse to publish unless:
- the current working tree is for the master branch
- it is completely up-to-date with the origin master
- it is clean
- it is still clean after jekyll is used to rebuild the site from scratch

The idea is that the gh-pages branch should always reflect the content of the latest merged master branch. We can use the "-f" option, e.g., to quickly roll back to a prior commit on master, or whatever, but it should be very uncommon.

### CODE REVIEW

**Comment by andylowry** [comment]
@tedepstein It would probably make sense, once this is published from a merged master, to establish `docs.reprezen.com` as a CNAME for `reprezen.github.io` in DNS. At the same time I'll need to make a small change to the site, adding a marker file so github will know that incoming requests for host `docs.reprezen.com` should serve from our `docs` repo.

**Comment by tedepstein** [comment]
@andylowry , I don't think any of us could do a meaningful review without a walkthrough.  And I'm not sure it's really warranted at this point.  So I'll concentrate on QA, assuming http://reprezen.github.io/docs/ is current with this task branch.

Some initial comments:
- I think the overall look & feel of the home page at http://reprezen.github.io/docs/ is just fine for a documentation site.  No urgency to do anything fancy here in the near term.  It's a lot prettier than our support site!
- The RepreZen logo in the header is not consistent with the usual proportions and colors.  Please use this one, scaled down to a similar width as the one you're using: logo_with_trademark
- The word "Portal" is a little dated.  I think you can leave that out and just have the word "Documentation" after the logo.
- Link to RAPID-ML Quick Reference Guide is broken.  That doc is not currently hosted online anywhere.  It probably belongs in [rapid-api.org](), alongside the spec.  But AFAIK, rapid-api.org doesn't have much in the way of scripting, change management, continuous integration, etc.  @daffinm can tell you what there is to know.
  - Since we don't have plans to jekyllize the RAPID-API site right now, I think you could skip that link, or include the Quick Reference Guide directly in the docs site if that's easy to do.  But this is not important right now, so please the expedient thing, whatever that turns out to be.
  - If you do decide to host it here, please name the link "Learning RAPID-ML."  One less thing to do when we rename the doc, as specified in [ZEN-2487](https://modelsolv.atlassian.net/browse/ZEN-2487).
- I think you could add the QRC to Core Docs.
- The Training videos section is nice to have, but it's going to be extra maintenance as we change the videos.  Maybe it's better to just have 3 links:
  - RepreZen YouTube Channel
  - Video Series: Working with RepreZen API Studio
  - Video Series: RAPID-ML

**Comment by tedepstein** [comment]
We need a copyright notice in the footer.  This should apply to all pages in the site, including documentation pages and the docs home page:

> © 2016 ModelSolv, Inc.  All rights reserved.

**Comment by tedepstein** [comment]
@andylowry , @daffinm , a question about versioning:

As you said in the comment, this site will always reflect what's currently in the master branch.  However, there are 2 problems:
1. We need to be able to work on new documentation for a new release, while that release is in development, and have someplace to view it.  Would we just look at the .adoc files inside the working tree, until it's published?
2. Inbound links from API Studio menus, dashboard, etc., should always go to matching doc version. 

In  the [rapid-api.org]() site, we used something similar to "release links".  If you look at http://rapid-api.org/rapid-ml/spec/, you can see a hint of the structure.  IIRC:
- 1.0.1 is a physical directory containing the current docs. 
- 1.0 is a symlink to 1.0.1.  There could be other 1.0.x directories with versions that are ahead of the 1.0 version (under development) or behind (tied to previous software releases).
- beta is a symlink that current resolves to 1.0.1, but could resolve to a later release.
- current is a symlink that currently resolves to 1.0.1.

@daffinm , please let me know if that's wrong.

Should we do something similar with this docs site, to address the second requirement, above?  

And should we consider building additional releases of the docs site, by default or on request, for task or topic branches under development, to address the first requirement?

**Comment by tedepstein** [comment]
Merging, so I can easily see what's changed in the other PRs.

**Comment by andylowry** [comment]
@tedepstein wrote:

> The RepreZen logo in the header is not consistent with the usual proportions and colors. Please use this one,

Thanks, much better. Prior was just a vertically-stacked logo I found on another website, photoshopped to be horizontal.

>  Link to RAPID-ML Quick Reference Guide is broken.

Actually, I think the link is fine, but I named it wrong. It's the Quick Reference _Card_ not _Guide_. I just copied links I found in API Studio for the core docs and screwed that up. I'll rename that link and copy the QSG to this site and link it in as "Learning RAPID-ML". If/when we publish it somewhere else I'll remove the embedded version and fix the links.

> I think you could add the QRC to Core Docs.

Yup. Part of the same mistake as with QRG

> The Training videos section is nice to have, but it's going to be extra maintenance as we change the videos.

It's all of about a 30-second change, not including JIRA/Github overhead. Menu bar and home page, as well as links inside articles, are all generated automatically from a JSON file. A typical video entry looks like this:

```
  - title: Introducing RepreZen API Studio
    url: https://www.youtube.com/watch?v=aYYChcU2oJI&index=1&list=PLLMXvAoF1MNYQUezbEEEFfL5Lt8EXTOSg
    type: external
```

So if maintenance effort is your only concern, I'd say let's stick with the full list.

> We need a copyright notice in the footer

Done

> We need to be able to work on new documentation for a new release, while that release is in development, and have someplace to view it

My idea for this was to have a separate repo, e.g. `RepreZen/docs-qa`, whose gh-pages branch would house this content. We can create it and tear it down as needed. And if we needed more than one we could just create and tear down others as needed.

I would add a `-qa` flag to my publish script which would manage all this and also skip the normal policy checks that otherwise insist on a clean, up-to-date master branch. The `-qa` option could take an optional argument which would name the qa repo defaulting to `docs-qa`.

> Inbound links from API Studio menus, dashboard, etc., should always go to matching doc version

This one is a bit more complicated. The same idea could work, but it would mean hanging on to more and more repos over time, which seems messy. Also we should be able to advertise docs.reprezen.com as a useful site independent of links from the product. I think it would seem strange for the internal product links to point to something different.

I don't think that most products have version-specific documentation sites, and I don't think most users expect them.

An alternative would be to add a minor caution on the home page pointing out that information in some of the articles may not apply to every release of the product, and include version-specific pointers in articles where it seems particularly important (but not overdoing this as it can get extremely disruptive - or maybe collecting them as addenda at the end of the article?). We could also add a "last updated" date to each article and/or an "as of version" indicator.

**Pull request merged**
